### ISSUE TITLE
Typo in interface.py, line 54

### ISSUE THREAD

**Issue by MarioP03** [IMC-UAS-Krems/2024-DBST2VO-Public#2]
@alessiogambi 
There is a typo in the function name **"get_purchase_hystory"**, on line 54 in file "interface.py" in the assignment.

![typo_interfacepy](https://github.com/IMC-UAS-Krems/2024-DBST2VO-Public/assets/160149523/7b26ec11-73ad-4b0a-afdd-dc1c2159f8a0)

**Comment by alessiogambi** [comment]
Fixed. Thanks
