### ISSUE TITLE
test_delete_user_from_an_empty_db small problem 

### ISSUE THREAD

**Issue by VakaruGIT** [IMC-UAS-Krems/2024-DBST2VO-Public#21]
public test:

def test_delete_user_from_an_empty_db(rdbms_connection, rdbms_admin_connection, neo4j_db):
    t = Traits(rdbms_connection, rdbms_admin_connection, neo4j_db)
    user_email = "user@email.org"
    user_details = None
    # Skip the test if the DB is NOT empty
    if len(utils.get_all_users()) == 0:
        pytest.skip("Skip this test because the DB is NOT empty !")
    t.add_user(user_email, user_details)
    utils = TraitsUtility(rdbms_connection, rdbms_admin_connection, neo4j_db)
    assert len(utils.get_all_users()) == 1, f"User {user_email} not inserted"
    # Delete the user
    t.delete_user(user_email)
    assert len(utils.get_all_users()) == 0, f"User {user_email} not correctly removed"
    
    This test raises an error !!!
     
  FAILED public/tests/test_public_tests.py::test_delete_user_from_an_empty_db - UnboundLocalError: cannot access local variable 'utils' where it is not associated with a value   
    
    
    but after it is changed to : 
     
    def test_delete_user_from_an_empty_db(rdbms_connection, rdbms_admin_connection, neo4j_db):
    t = Traits(rdbms_connection, rdbms_admin_connection, neo4j_db)
    utils = TraitsUtility(rdbms_connection, rdbms_admin_connection, neo4j_db)
    user_email = "user@email.org"
    user_details = None
    # Skip the test if the DB is NOT empty
    if len(utils.get_all_users()) != 0:
        pytest.skip("Skip this test because the DB is NOT empty !")

    t.add_user(user_email, user_details)
    assert len(utils.get_all_users()) == 1, f"User {user_email} not inserted"
    # Delete the user
    t.delete_user(user_email)
    assert len(utils.get_all_users()) == 0, f"User {user_email} not correctly removed"
    
    it works and is not raising the same error 
    @alessiogambi

**Comment by alessiogambi** [comment]
Thanks. I'll merge you fix soon

**Comment by VakaruGIT** [comment]
@alessiogambi 
the test gets skipped now if the database is empty instead of NOT empty 
the corrected test should be
```python
def test_delete_user_from_an_empty_db(rdbms_connection, rdbms_admin_connection, neo4j_db):
    t = Traits(rdbms_connection, rdbms_admin_connection, neo4j_db)
    utils = TraitsUtility(rdbms_connection, rdbms_admin_connection, neo4j_db)
    
    user_email = "user@email.org"
    user_details = None
    # Skip the test if the DB is NOT empty
    if len(utils.get_all_users()) != 0: ####### HERE IS WHAT NEEDS TO BE MODIFIED FROM == 0 TO != 0
        pytest.skip("Skip this test because the DB is NOT empty !")

    t.add_user(user_email, user_details)
    utils = TraitsUtility(rdbms_connection, rdbms_admin_connection, neo4j_db)
    assert len(utils.get_all_users()) == 1, f"User {user_email} not inserted"
    # Delete the user
    t.delete_user(user_email)
    assert len(utils.get_all_users()) == 0, f"User {user_email} not correctly removed"
```

**Comment by alessiogambi** [comment]
@VakaruGIT thanks. Now it should be ok.
