### ISSUE TITLE
TraitsUtility class

### ISSUE THREAD

**Issue by gabrielalaa** [IMC-UAS-Krems/2024-DBST2VO-Public#25]
Hi. My colleague Alexandra Elena and I encountered a problem. In expected content, in the Traits Utility class, the generate_sql_initizalization_code method is expected to be a static method.
But in the interface in TraitsUtilityInterface, the decorator of this method is missing.
![Screenshot (807)](https://github.com/IMC-UAS-Krems/2024-DBST2VO-Public/assets/148258515/f4217b18-f3aa-46fb-ae0e-6a61b67b3bbb)

**Comment by alessiogambi** [comment]
@gabrielalaa 
Does it work if you only add the @staticmethod decorator to your implementation?

**Comment by gabrielalaa** [comment]
Yes, now it is working. I had to restart PyCharm
