### ISSUE TITLE
Conftest issue

### ISSUE THREAD

**Issue by AlexandraIanE** [IMC-UAS-Krems/2024-DBST2VO-Public#26]
Me and my colleague Gabriela found an issue within the fixtures file, line 117, you are trying to close the cursor but it is not declared global. I think it would be good to declare it before the try as cursor = None.
![Screenshot (795)](https://github.com/IMC-UAS-Krems/2024-DBST2VO-Public/assets/152512116/776b4ce2-2288-4ba5-ab79-31ee3cafaf1a)

**Comment by alessiogambi** [comment]
Good catch. Checking whether the connection is connected is safe enough, but let me declare cursor = None before the try block.
