### ISSUE TITLE
Price calculation

### ISSUE THREAD

**Issue by eszterballabas** [IMC-UAS-Krems/2024-DBST2VO-Public#6]
What are the criteria for calculating prices?

**Comment by alessiogambi** [comment]
@eszterballabas: Here's the description on how the price can be calculated. I already merged in the README.md see: 
[here](https://github.com/IMC-UAS-Krems/2024-DBST2VO-Public/commit/a8c81520ebddcc1f11ccbe86361612dd540466e9#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5).

------
The estimated price is the overall (fixed) cost of the travel, which depends on the travel distance/time (`travel_price = travel time / 2`), and the (variable) cost for seat reservation, which depends on how many seats should be reserved (`reservation_price=number of trains * 2`).

For example, if the user travels with Train 1 from A to B to C and then boards Train 2 to reach D, the estimated price for the ticket plus reservations is:
- ```travel_price = [ tt(A,B) + tt(B,C) + tt(C,D) ] / 2```, where tt is the travel time from two stations (without counting the waiting time at each station or any delay)
- ```reservation_price = 2 * 2```

> Note: the actual price might be different if some seats cannot be reserved due to high demand

------
